cabal-version:       3.16
name:                h99
version:             0.1.0
synopsis:            Answers for H-99.
description:
  Answers for H-99: Ninety-Nine Haskell Problems, tested with doctest.
homepage:            https://github.com/cohei/h99
license:             BSD-3-Clause
license-file:        LICENSE
author:              TANIGUCHI Kohei
maintainer:          a.d.xvii.kal.mai@gmail.com
copyright:           2016 TANIGUCHI Kohei
extra-doc-files:     README.md

source-repository head
  type:     git
  location: https://github.com/cohei/h99

common common
  build-depends:       base >= 4.7 && < 5
  default-language:    Haskell2010

library
  import:              common
  exposed-modules:     H99
  build-depends:       random
  ghc-options:
    -Wall
    -Wcompat
    -Wcpp-undef
    -Widentities
    -Wimplicit-lift
    -Wmissing-deriving-strategies
    -Wmissing-export-lists
    -Wmissing-exported-signatures
    -Wmissing-home-modules
    -Wmissing-import-lists
    -Wmissing-kind-signatures
    -Wmissing-local-signatures
    -Wmonomorphism-restriction
    -Wpartial-fields
    -Wredundant-constraints
    -Wsafe
    -Wunticked-promoted-constructors
    -Wunused-packages
    -Wunused-type-patterns
    -fdefer-typed-holes

test-suite doctest
  import:              common
  main-is:             doctest.hs
  build-depends:       doctest
