name: Testing

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.6.2'
      - name: Build
        run: cabal build --enable-tests
      - name: Run tests
        run: cabal test
